[types]
IntType = "int"
BigIntType = "bigint" #No utilizado
StringType = "string"
BoolType = "bool"
FloatType = "float"
DoubleType = "double" #No utilizado
CharType = "char"
VoidType = "void"

[keywords]
If = "if"
Else = "else"
While = "while"
For = "for" #No utilizado
Switch = "switch"
Case = "case"
Default = "default"
Function = "function"
Return = "return"

[literals]
True = "true"
False = "false"

[functions]
Print = "print"
Println = "println" #No utilizado
Input = "input"